**Linear Algebra with scipy**

SciPy is a collection of mathematical algorithms and convenience functions built on the Numpy extension of Python. `scipy.linalg` contains  linear algebra routines from ATLAS LAPACK and BLAS libraries.

All of these linear algebra routines expect an object that can be converted into a 2-dimensional array. The output of these routines is also a two-dimensional array.

In [1]:
import numpy as np
from scipy import linalg

A = np.array([[1,2],[3,4]])
print(A) ## A 2d array
print(A.shape) ## dimensions of A
print(A[:,1])  ## second column of A
print(A[0,:])  ## First row of A

Ainv = linalg.inv(A)
print(Ainv)

print(Ainv * A) ## Not matrix multiplication
print(np.dot(Ainv, A)) ## matrix multiplication

b = np.array([[5,6]]) #2D array
print(b)
print(b.T) ## Transpose operator

A.dot(b.T) #matrix multiplication
b = np.array([5,6]) #1D array
b.T  #not matrix transpose!
A.dot(b)  #does not matter for multiplication

[[1 2]
 [3 4]]
(2, 2)
[2 4]
[1 2]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[-2.   2. ]
 [ 4.5 -2. ]]
[[  1.00000000e+00   0.00000000e+00]
 [  1.11022302e-16   1.00000000e+00]]
[[5 6]]
[[5]
 [6]]


array([17, 39])

**Solving Linear systems**

In [2]:
## Solving linear systems
A = np.array([[0, 2, 1], [3, -1, 2], [1, -1, 1]])
b = np.array([[2], [-3], [-3]])

x = linalg.solve(A, b)
print('x = \n', x, '\n')

print('Ax - b = \n', np.dot(A, x) - b, '\n')

xp = linalg.inv(A).dot(b) # slow
print('xp  = \n', xp, '\n')

x = 
 [[ 1.]
 [ 2.]
 [-2.]] 

Ax - b = 
 [[  0.00000000e+00]
 [  0.00000000e+00]
 [  4.44089210e-16]] 

xp  = 
 [[ 1.]
 [ 2.]
 [-2.]] 



**Sovling tri-diagonal system of cubic splines**

In [3]:
from scipy.sparse import diags
## solving diagonal systems (cubic spline equations)
x = np.arange(-np.pi/2., np.pi/2., 0.4)
y = np.cos(x) 

n = x.shape[0]
A = np.identity(n)
b = np.zeros_like(y)
    
h = x[1:] - x[:-1]
main_diag  = np.concatenate([[1], 2. * (h[1:] + h[:-1]), [1]])
upper_diag = np.concatenate([[0], h[1:]])
lower_diag = np.concatenate([h[:-1], [0]])
diagonals  = np.array([upper_diag, main_diag, lower_diag])

A = diags(diagonals, [1, 0, -1]).toarray()
print('A = \n', A, '\n')


b0 = [(3. / h[i]) * (y[i+1] - y[i]) - (3. / h[i - 1]) * (y[i] - y[i-1]) for i in range(1,n-1)]
b = np.concatenate([[0], b0, [0]])

c = linalg.solve(A, b)
print('c = \n', c, '\n')


A = 
 [[ 1.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.4  1.6  0.4  0.   0.   0.   0.   0. ]
 [ 0.   0.4  1.6  0.4  0.   0.   0.   0. ]
 [ 0.   0.   0.4  1.6  0.4  0.   0.   0. ]
 [ 0.   0.   0.   0.4  1.6  0.4  0.   0. ]
 [ 0.   0.   0.   0.   0.4  1.6  0.4  0. ]
 [ 0.   0.   0.   0.   0.   0.4  1.6  0.4]
 [ 0.   0.   0.   0.   0.   0.   0.   1. ]] 

c = 
 [ 0.         -0.1972606  -0.36371874 -0.47139108 -0.50975091 -0.4485558
 -0.38773973  0.        ] 



**A = PLU Factorization**

In [4]:
## LU decomposition
A = np.array([[1., 3., 2.], [1., 4., 5.], [2., 3., 6.]])
P, L, U = linalg.lu(A)
print('A = \n', A, '\n')
print('P = \n', P, '\n')
print('L = \n', L, '\n')
print('U = \n', U, '\n')

print('PLU = \n', np.dot(P, np.dot(L,U)), '\n')

A = 
 [[ 1.  3.  2.]
 [ 1.  4.  5.]
 [ 2.  3.  6.]] 

P = 
 [[ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]] 

L = 
 [[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [ 0.5  0.6  1. ]] 

U = 
 [[ 2.   3.   6. ]
 [ 0.   2.5  2. ]
 [ 0.   0.  -2.2]] 

PLU = 
 [[ 1.  3.  2.]
 [ 1.  4.  5.]
 [ 2.  3.  6.]] 



**Singular Value Decomposition (SVD)**

In [5]:
## Singular Value Decomposition
A = np.array([[14., 2.], [4., 22.], [16., 13.]])
U, Sig, VT = linalg.svd(A)

print('A = \n', A, '\n')
print('U = \n', U, '\n')
print('Sig = \n', Sig, '\n')
print('Sig = \n', linalg.diagsvd(Sig,U.shape[0],VT.shape[0]), '\n')
print('VT = \n', VT, '\n')

## diagsvd(S, M, N) creates an M X N diagonal matrix with diagonal S
print(np.dot(U, np.dot(linalg.diagsvd(Sig,U.shape[0],VT.shape[0]), VT)))

A = 
 [[ 14.   2.]
 [  4.  22.]
 [ 16.  13.]] 

U = 
 [[-0.33333333  0.66666667 -0.66666667]
 [-0.66666667 -0.66666667 -0.33333333]
 [-0.66666667  0.33333333  0.66666667]] 

Sig = 
 [ 30.  15.] 

Sig = 
 [[ 30.   0.]
 [  0.  15.]
 [  0.   0.]] 

VT = 
 [[-0.6 -0.8]
 [ 0.8 -0.6]] 

[[ 14.   2.]
 [  4.  22.]
 [ 16.  13.]]


**Solving over determined linear systems with least squares method**

Consider a system of linear equations  $Ax=b$ , where  $A$ is $m \times n$, $m \geq n$ and full (column) rank. This kind of system is called overdetermined, as it has more equations than unknowns (most of the times no solution). The least-squares solution is to find $x$ that minimizes $||Ax - b||$. This can be acheived by

$$
Ax = b \iff A^{T}A x = A^{T}b \iff x = (A^{T}A)^{-1}A^{T} b
$$
 
The matrix $A^{\dagger} = (A^{T}A)^{-1}A^{T}$ is called Moore–Penrose pseudoinverse.

In [7]:
A = np.random.randn(5,3)
print('A = \n', A, '\n')
B = linalg.pinv(A)
print('B = \n', B, '\n')
Ap = np.dot(linalg.inv(np.dot(A.T,A)),A.T)
print('Ap = \n', Ap, '\n')

print('Ap x A = \n', np.dot(Ap, A), '\n')

A = 
 [[-0.66065865 -0.67905565 -0.32887524]
 [ 0.69036457  0.44965809  1.13392819]
 [-1.36170749 -0.13187252 -0.65828684]
 [ 0.67095441  0.26218896 -0.7917989 ]
 [ 0.10753987  0.98940728 -1.80366061]] 

B = 
 [[ 0.09034681 -0.1370775  -0.6209266   0.47370293 -0.08398394]
 [-0.59062314  0.59346877  0.43048546 -0.3984375   0.49859255]
 [-0.19745998  0.34868783  0.10049585 -0.31777101 -0.19638822]] 

Ap = 
 [[ 0.09034681 -0.1370775  -0.6209266   0.47370293 -0.08398394]
 [-0.59062314  0.59346877  0.43048546 -0.3984375   0.49859255]
 [-0.19745998  0.34868783  0.10049585 -0.31777101 -0.19638822]] 

Ap x A = 
 [[  1.00000000e+00   1.10428043e-16   1.66533454e-16]
 [  2.45641610e-16   1.00000000e+00  -2.22044605e-16]
 [  1.87350135e-16   2.77555756e-17   1.00000000e+00]] 



**General case: non-full ranked or underdetermined systems**
For the system $Ax = b$, where $A$ is $m \times n$, $m < n$ or if $rank(A) < n$, the $n \times n$ matrix $A^{T}A$ is non invertible. This is because $rank(A^{T}A) = rank(A) < n$. In such cases, we can still define a pseudo inverse using singular value decomposition. Let $A = U \Sigma V^{T}$ with $U$, $m \times m$ orthogonal, $\Sigma$, $m \times n$ diagonal and $V$, $n \times n$ orthogonal.

$$
Ax = b \iff U \Sigma V^{T} x = b \iff \Sigma V^{T} x = U^{T}b
$$

Define $y = V^{T} x$ and let $b^{\prime} = U^{T}b$. Then the system $Ax = b$ is equivalent to the diagonal system:

$$\Sigma y = b^{\prime}$$. 

If we can solve this diagonal system for $y$, we can then compute $x = Vy$. The diagonal matrix $\Sigma$ is of the form

$$
\Sigma = \begin{bmatrix} \tilde{\Sigma} & 0\\
0 & 0\\ 
\end{bmatrix}
$$

with $\tilde{\Sigma}$ is an $r \times r$ diagonal matrix of the form
$$
\tilde{\Sigma} = \begin{bmatrix} 
\sigma_1 & 0& \cdots &0\\ 
0& \sigma_2 &  \cdots & 0\\
\vdots & \vdots & \cdots & \vdots\\
0& 0 &  \cdots & \sigma_r \\
\end{bmatrix}
$$

where $\sigma_1 \geq \cdots \geq\sigma_r > 0$ are the non-zero singular values of $A$, with $r \leq \min(m,n)$. Since $\Sigma$ may not be invertible due to singularities, we resort to defining a pseudo inverse of $\Sigma$ as

$$
\Sigma^{-1} = \begin{bmatrix} \tilde{\Sigma}^{-1} & 0\\
0 & 0\\ 
\end{bmatrix}
$$
and 
$$
\tilde{\Sigma}^{-1} = \begin{bmatrix} 
1/\sigma_1 & 0& \cdots &0\\ 
0& 1/\sigma_2 &  \cdots & 0\\
\vdots & \vdots & \cdots & \vdots\\
0& 0 &  \cdots & 1/\sigma_r \\
\end{bmatrix}
$$

Now, let $\hat{y} = \Sigma^{-1}b^{\prime}$. This solution minimizes $||\Sigma y - b^{\prime}||$ with the additional constraint that $||\hat{y}||$ is mimimum among all possible solutions. The pseudoinverse of $A$ can be obtained by $A^{\dagger} = V \Sigma^{-1} U^{T}$.



In [8]:
A = np.array([[1., 0., -1., 2.], [1., 1., 1., -1.], [0., -1., -2., 3.], [5., 2., -1., 4.], [-1., 2., 5., -8.]])
b = np.array([[-1.], [2.], [-3.], [1.], [7.]])
A.shape
print('A = \n', A, '\n')

U, Sig, VT = linalg.svd(A)
V = VT.T
print('Sig = \n', Sig, '\n')

epsilon = 10.**(-12)

rank = sum(Sig > epsilon)

siginv = np.zeros_like(Sig)
siginv[Sig > epsilon] = 1 / Sig[Sig > epsilon]

m = A.shape[0]
n = A.shape[1]
SigInv = linalg.diagsvd(siginv, n, m)
print('SigInv = \n', SigInv, '\n')

Ap = np.dot(V, np.dot(SigInv, U.T))
B = linalg.pinv2(A)


print('Ap = \n', Ap, '\n')
print('B = \n', B, '\n')


x = np.dot(Ap, b)
print('x = \n', x, '\n')

print('Ax - b = \n', np.dot(A, x) - b)


A = 
 [[ 1.  0. -1.  2.]
 [ 1.  1.  1. -1.]
 [ 0. -1. -2.  3.]
 [ 5.  2. -1.  4.]
 [-1.  2.  5. -8.]] 

Sig = 
 [  1.15923770e+01   5.44213162e+00   7.76763483e-16   2.46098258e-16] 

SigInv = 
 [[ 0.08626359  0.          0.          0.          0.        ]
 [ 0.          0.18375153  0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]] 

Ap = 
 [[ 0.01708543  0.04170854 -0.02462312  0.13467337  0.0321608 ]
 [ 0.00653266  0.03065327 -0.0241206   0.08090452  0.04170854]
 [-0.0040201   0.01959799 -0.02361809  0.02713568  0.05125628]
 [ 0.01457286 -0.00854271  0.02311558  0.02663317 -0.06080402]] 

B = 
 [[ 0.01708543  0.04170854 -0.02462312  0.13467337  0.0321608 ]
 [ 0.00653266  0.03065327 -0.0241206   0.08090452  0.04170854]
 [-0.0040201   0.01959799 -0.02361809  0.02713568  0.05125628]
 [ 0.01457286 -0.00854271  0.02311558  0.02663317 -0.06080402]] 

x = 
 [[ 0.5]
 [ 0.5]
 [ 0.

Note that for full rank matrices, both SVD pseudo inverse and $A^{\dagger} = (A^{T}A)^{-1}A^{T}$ are the same:

In [9]:
A = np.random.randn(3, 2)
print('A = \n', A, '\n')
Ap1 = linalg.pinv(A)
print('AP1 = \n', Ap1, '\n')
Ap2 = linalg.pinv2(A)
print('AP2 = \n', Ap2, '\n')


A = 
 [[-0.73781883 -0.07301793]
 [ 0.87027489 -1.15418128]
 [ 0.38428242 -1.50793447]] 

AP1 = 
 [[-0.95953704  0.47588969 -0.31778541]
 [-0.42675692 -0.11797433 -0.55219597]] 

AP2 = 
 [[-0.95953704  0.47588969 -0.31778541]
 [-0.42675692 -0.11797433 -0.55219597]] 



**General SVD solver for linear systems**

In [10]:
def svd_solver(A, b, epsilon = 10.**-12):
    m = A.shape[0]
    n = A.shape[1]

    U,Sig,VT = linalg.svd(A)
    V = VT.T
    
    siginv = np.zeros_like(Sig)
    siginv[Sig > epsilon] = 1 / Sig[Sig > epsilon]

    SigInv = linalg.diagsvd(siginv, n, m)
    Ap = np.dot(V, np.dot(SigInv, U.T))
    
    x = np.dot(Ap, b)
    return(x)

**Spectral Decomposition**

In [18]:
A = np.array([[2,1,4],[1,3,5],[4,5,1]])

Lam, U = linalg.eig(A)
print(U)
print(Lam)

Lam = diags(Lam, 0).toarray()
S = np.dot(U, np.dot(Lam, U.T))
print(S)

[[-0.46155521 -0.78186489 -0.41911107]
 [-0.62175801  0.62210048 -0.47582346]
 [-0.63275885 -0.04096687  0.77326448]]
[ 8.83080456+0.j  1.41392304+0.j -4.24472760+0.j]
[[ 2.+0.j  1.+0.j  4.+0.j]
 [ 1.+0.j  3.+0.j  5.+0.j]
 [ 4.+0.j  5.+0.j  1.+0.j]]
